--CRIANDO TABELAS

CREATE TABLE PRODUTOS (
   IDP NUMBER(3) PRIMARY KEY AUTO INCREMENT,
   NOMEP VARCHAR2(120),
   CATEGORIA VARCHAR2(120)
 );

CREATE TABLE LOCAIS (
   IDLOC NUMBER(3) PRIMARY KEY,
   CIDADE VARCHAR2(120),
   ESTADO CHAR (2),
   PAIS VARCHAR2(120)
 );
 
CREATE TABLE TEMPOS (
   IDTEMPO NUMBER(3) PRIMARY KEY,
   SEMANA NUMBER(1),
   MES NUMBER(2),
   TRIMESTRE NUMBER (1),
   ANO NUMBER (4),
   FLAG_FERIADO NUMBER(1)
 );

CREATE TABLE VENDAS (
   IDP NUMBER(3),
   IDTEMPO NUMBER(3),
   IDLOC NUMBER(3),
   VENDAS NUMBER (4)
 );
 

INSERT INTO PRODUTOS(IDP, NOMEP, CAATEGORIA)
VALUES (DEFAULT,'SABONETE','HIGIENE');
INSERT INTO PRODUTOS(IDP, NOMEP, CAATEGORIA)
VALUES (DEFAULT,'SHAMPOO','HIGIENE');
INSERT INTO PRODUTOS(IDP, NOMEP, CAATEGORIA)
VALUES (DEFAULT,'CONDICIONADOR','HIGIENE');

--INSERINDO DADOS

INSERT INTO LOCAIS
VALUES (1,'PIRATININGA','SP','BRASIL');
INSERT INTO LOCAIS
VALUES (2,'PIRATININGA','SP','BRASIL');
INSERT INTO LOCAIS
VALUES (3,'PIRATININGA','SP','BRASIL');
 
INSERT INTO TEMPOS
VALUES (1,1,01,1,1990,0);
INSERT INTO TEMPOS
VALUES (2,4,06,2,2000,0);
INSERT INTO TEMPOS
VALUES (3,2,12,4,1999,1); 

INSERT INTO VENDAS
VALUES (1,3,3,1001);
INSERT INTO VENDAS
VALUES (2,3,3,1001);
INSERT INTO VENDAS
VALUES (3,3,3,1001);

--SELECT CÚBICO

SELECT T.ANO, L.ESTADO, SUM(V.VENDAS)
FROM VENDAS V, TEMPOS T, LOCAIS L
WHERE V.IDTEMPO= T.IDTEMPO
AND V.IDLOC = L.IDLOC
GROUP BY CUBE (T.ANO, L.ESTADO);
